name: Local Install Checks
on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SPARSEZOO_TEST_MODE: "true"
  NM_DISABLE_ANALYTICS: "true"

jobs:
  local-install-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "neuralmagic/sparsezoo"
          path: "sparsezoo"
      - name: "⚙️ Install sparsezoo dependencies"
        run: pip install sparsezoo/
      - uses: actions/checkout@v2
      - name: "⚙️ Install local deepsparse"
        run: pip3 install .
      - name: "deepsparse.benchmark"
        run: deepsparse.benchmark zoo:cv/classification/mobilenet_v1-1.0/pytorch/sparseml/imagenet/pruned_quant-moderate -w 1 -t 1
  local-develop-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "neuralmagic/sparsezoo"
          path: "sparsezoo"
      - name: "⚙️ Install local develop deepsparse"
        run: |
          python3.8 -m venv venv-dev
          source venv-dev/bin/activate
          pip install sparsezoo/
          pip install -e .
      - name: "deepsparse.benchmark"
        run: |
          source venv-dev/bin/activate
          deepsparse.benchmark zoo:cv/classification/mobilenet_v1-1.0/pytorch/sparseml/imagenet/pruned_quant-moderate -w 1 -t 1
